### ISSUE TITLE
company-stan no longer available in MELPA

### ISSUE THREAD

**Issue by RishiSadhir** [stan-dev/stan-mode#60]
Hi team,

Looks like company-stan is no longer available in MELPA.

http://melpa.org/#/?q=company-stan

**Comment by kaz-yos** [comment]
Actually, `company-stan`, `eldoc-stan`, and `flycheck-stan` have not been on MELPA, yet. They just went through the review by the MELPA maintainer team. I need to fix some minor points before they can be approved.

`company-stan`: https://github.com/melpa/melpa/pull/6449
`eldoc-stan`: https://github.com/melpa/melpa/pull/6450
`flycheck-stan`: https://github.com/melpa/melpa/pull/6451

 Due to the impending NIH grant deadline, I will come back to this early to mid-November. 

Meanwhile, you can install via Github although it involves a few more steps.

https://github.com/stan-dev/stan-mode#via-github

**Comment by RishiSadhir** [comment]
Thanks for the update and all your work, kaz-yos!

**Comment by kaz-yos** [comment]
I have addressed the issues with `company-stan` and `eldoc-stan` that the MELPA reviewer pointed out. So they should come to MELPA soon. I am still working on `flycheck-stan`.

**Comment by kaz-yos** [comment]
`company-stan` has come to MELPA (https://melpa.org/#/company-stan). `eldoc-stan` and `flycheck-stan` should be coming soon.

**Comment by kaz-yos** [comment]
The new packages are on MELPA now:
- https://melpa.org/#/company-stan
- https://melpa.org/#/eldoc-stan
- https://melpa.org/#/flycheck-stan

The v10.0.0 Release has been made, so it should come to MELPA Stable, too.
